# https://docs.travis-ci.com/user/languages/java/
language: java
jdk: openjdk11

#https://dzone.com/articles/travis-ci-tutorial-java-projects
cache:
  directories:
    - $HOME/.m2

#https://docs.travis-ci.com/user/database-setup/#PostgreSQL
before_script:
  - psql -c 'create database petProject' -U postgres
  - psql -c 'create user "postgres"; grant all privileges on database petProject to "postgres" -U portgres

#https://docs.travis-ci.com/user/customizing-the-build#Building-Specific-Branches
branches:
  only:
    - master

#https://stackoverflow.com/a/49852690/548473
services:
  - postgresql

#https://docs.travis-ci.com/user/environment-variables#Default-Enviroment-Variables
env:
  -PETPROJECT_ROOT=$TRAVIS_BUILD_DIR

#https://docs.travis-ci.com/user/notifications#Configuring-email-notifications
#notifications:
# email: false

